<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise:非同期処理</title>
</head>
<body>
<script>

/*  1.3.2. promiseオブジェクトに処理を書く

    先ほどの作成したpromiseオブジェクトを返す関数を実際に使ってみましょう。*/

    fetchURL("https://httpbin.org/get"); // => promiseオブジェクトが返ってくる

/*  Promises Overviewでも簡単に紹介したようにpromiseオブジェクトは
    幾つかインスタンスメソッドを持っており、 これを使いpromiseオブジェクトの
    状態に応じて一度だけ呼ばれるコールバックとなる関数を登録します。

    promiseオブジェクトに登録する処理は以下の2種類が主となります。

    1.promiseオブジェクトがresolveされた時の処理(onFulfilled)

    2.promiseオブジェクトがrejectされた時の処理(onRejected)

    
    Figure 2. promise value flow

                resolve   value
                ------------------onFulfilled
                |  
    Pending-----|
                |
                ------------------onRejected
                reject     error


    まずは、fetchURLで通信が成功して値が取得できた場合の処理を書いてみましょう。

    この場合の通信が成功したというのは、resolveされたことにより 
    promiseオブジェクトがFulfilledの状態になった時ということですね。

    resolveされた時の処理は、.thenメソッドに呼びたい関数を渡すことで行えます。*/

    const URL = "https://httpbin.org/get";

    fetchURL(URL).then((value) => { 

        console.log(value);

    });


/*  分かりやすくするため関数にonFulfilledという名前を付けています

    fetchURL関数内でresolve(req.responseText);
    によってpromiseオブジェクトが解決されると、 
    値と共にonFulfilled関数が呼ばれます。

    このままでは通信エラーが起きた場合などに何も処理がされないため、 
    今度は、fetchURLで何らかの問題があってエラーが起きた場合の処理を書いてみましょう。

    この場合のエラーが起きたというのは、rejectされたことよりpromiseオブジェクトが
    Rejectedの状態になった 時ということですね。

    rejectされた時の処理は、.then の第二引数 または .catchメソッドに
    呼びたい関数を渡すことで行えます。

    先ほどのソースにrejectされた場合の処理を追加してみましょう。*/

    URL = "https://httpbin.org/status/500"; 

    fetchURL(URL).then((value) => {

        console.log(value);

    }).catch((error) => { 

        console.error(error);

    });
    

/*  サーバはステータスコード500のレスポンスを返す
    
    分かりやすくするため関数onRejectedという名前を付けています

    fetchURLの処理中に何らかの理由で例外が起きた場合、
    または明示的にrejectされた場合に、 
    その理由(Errorオブジェクト)と共に.catchの処理が呼ばれます。

    .catchはpromise.then(undefined, onRejected)のエイリアスであるため、 
    同様の処理は以下のように書くこともできます。*/

        fetchURL(URL).then(onFulfilled, onRejected); 

/*  onFulfilled, onRejectedそれぞれは先ほどと同じ関数

    基本的には、.catchを使いresolveとrejectそれぞれを別々に処理した方がよいと考えられますが、 
    両者の違いについては then or catch? で紹介します。
    
    ※まとめ

    この章では以下のことについて簡単に紹介しました。

    new Promiseを使ったpromiseオブジェクトの作成

    .then や .catch を使ったpromiseオブジェクトの処理

    Promiseの基本的な書き方について学びました。
    他の多くの処理はこれを発展させたり、用意された静的メソッドを利用したものになります。

    ここでは、同様のことはコールバック関数を渡す形でもできるのに対して
    Promiseで書くメリットについては触れていませんでした。 
    
    次の章では、Promiseのメリットであるエラーハンドリングの仕組みを
    コールバックベースの実装と比較しながら見ていきたいと思います。

    */

    /*実行結果:Google Chrome-console

    */
</script>  
</body>
</html>